# Generated by Django 3.2.8 on 2021-10-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='departure',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
